spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mail:
    host: smtp.gmail.com
    port: 587
    username: mynameispukararyal@gmail.com
    password: guff rfuc mzqd bvdv

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4790